import type { Framework, MetricId, ProjectProfile } from './types.js'

/**
 * `perf.yml` — generated by the tool, edited by the user only if they want to (spec §3.3).
 *
 * Two numbers that are easy to confuse live here, and only one of them is configurable:
 *
 *  - **noise floor, 2%** — below this we do not report a delta at all. It is a property of what the
 *    instrument can resolve (hard rule 4), not a preference, so it is not exposed as config.
 *  - **threshold, default 5%** — the line at which a reported delta becomes a *verdict*. That is a
 *    team judgement, so it is configurable.
 */

export const NOISE_FLOOR_PERCENT = 2

export const CONFIG_FILENAME = 'perf.yml'

export interface PerfConfig {
  readonly detect: Framework
  readonly measure: readonly MetricId[]
  /** Boot the built app and measure routes (Layer 2a). CLI --no-serve overrides per run. */
  readonly serve: boolean
  /** Lighthouse browser metrics (needs Chrome). CLI --no-browser overrides per run. */
  readonly browser: boolean
  readonly threshold: string
  readonly block_merge: boolean
  readonly base: string
  readonly provider: string
  readonly model: string
}

export const DEFAULT_CONFIG: PerfConfig = {
  detect: 'unknown',
  measure: [],
  serve: true,
  browser: true,
  threshold: '5%',
  block_merge: false,
  base: 'main',
  provider: 'deepseek',
  model: 'deepseek-chat',
}

/** Config as the rest of the tool consumes it: percentages parsed, defaults filled in. */
export interface ResolvedConfig extends PerfConfig {
  readonly thresholdPercent: number
  readonly noiseFloorPercent: number
  /** Absolute path the config was read from, or null when running on defaults. */
  readonly sourcePath: string | null
  readonly warnings: readonly string[]
}

export function configFromProfile(profile: ProjectProfile): PerfConfig {
  return {
    ...DEFAULT_CONFIG,
    detect: profile.framework,
    measure: [...profile.supportedMetrics],
  }
}

/** Accepts `5%`, `5`, or `5.5%`. */
export function parsePercent(value: string): number | null {
  const match = /^\s*(\d+(?:\.\d+)?)\s*%?\s*$/.exec(value)
  if (!match?.[1]) return null
  const n = Number(match[1])
  return Number.isFinite(n) ? n : null
}
