import type { Framework, ProjectProfile } from './types.js'

/**
 * `perf.yml` — generated by the tool, edited by the user only if they want to (spec §3.3).
 *
 * Two numbers that are easy to confuse live here, and only one of them is configurable:
 *
 *  - **noise floor, 2%** — below this we do not report a delta at all. It is a property of what the
 *    instrument can resolve (hard rule 4), not a preference, so it is not exposed as config.
 *  - **threshold, default 5%** — the line at which a reported delta becomes a *verdict*. That is a
 *    team judgement, so it is configurable.
 */

export const NOISE_FLOOR_PERCENT = 2

export const CONFIG_FILENAME = 'perf.yml'

export interface PerfConfig {
  readonly detect: Framework
  /**
   * Which package of a monorepo to measure, relative to the workspace root. Null when the project
   * stands alone. In a multi-app workspace this is required — driftwatch refuses to pick (§9a).
   */
  readonly app: string | null
  /** Package manager override — the escape hatch when detection has no evidence to go on. */
  readonly package_manager: string | null
  /**
   * A command whose stdout is the AI-tier key (`op read op://vault/ai/key`). Lets a password
   * manager supply it without the key ever touching a file. The output is used and never stored.
   * A literal key here is refused, not accepted — perf.yml is committed (spec §9e).
   */
  readonly key_command: string | null
  /** Metric ids or class tokens ('route_latency', 'lcp', …) that count as KEY metrics. */
  readonly measure: readonly string[]
  /** Boot the built app and measure routes (Layer 2a). CLI --no-serve overrides per run. */
  readonly serve: boolean
  /** Lighthouse browser metrics (needs Chrome). CLI --no-browser overrides per run. */
  readonly browser: boolean
  /** Measure the AI's diff fix as a third side (M6). CLI --no-verify overrides per run. */
  readonly verify: boolean
  /** 'propose': open a fix PR when a verified diff RESTORES (or partially recovers) the metrics.
   *  Only restored/partial may ever open one; everything else stays in the comment. */
  readonly auto_fix: 'off' | 'propose'
  readonly threshold: string
  readonly block_merge: boolean
  readonly base: string
  readonly provider: string
  readonly model: string
}

export const DEFAULT_CONFIG: PerfConfig = {
  detect: 'unknown',
  app: null,
  package_manager: null,
  key_command: null,
  measure: [],
  serve: true,
  browser: true,
  verify: true,
  auto_fix: 'off',
  threshold: '5%',
  block_merge: false,
  base: 'main',
  provider: 'deepseek',
  model: 'deepseek-chat',
}

/** Config as the rest of the tool consumes it: percentages parsed, defaults filled in. */
export interface ResolvedConfig extends PerfConfig {
  readonly thresholdPercent: number
  readonly noiseFloorPercent: number
  /** Absolute path the config was read from, or null when running on defaults. */
  readonly sourcePath: string | null
  readonly warnings: readonly string[]
}

export function configFromProfile(profile: ProjectProfile): PerfConfig {
  const measure: string[] = [...profile.supportedMetrics]
  // Servable app with routes → the Layer 2a classes are promised and key.
  if (profile.commands.serve && profile.routes.length > 0) {
    measure.push('route_latency', 'lcp', 'tbt', 'fcp', 'transfer_size')
  }
  return {
    ...DEFAULT_CONFIG,
    detect: profile.framework,
    measure,
  }
}

/** Accepts `5%`, `5`, or `5.5%`. */
export function parsePercent(value: string): number | null {
  const match = /^\s*(\d+(?:\.\d+)?)\s*%?\s*$/.exec(value)
  if (!match?.[1]) return null
  const n = Number(match[1])
  return Number.isFinite(n) ? n : null
}
