import path from 'node:path'
import { writeFile } from 'node:fs/promises'
import { CONFIG_FILENAME, NOISE_FLOOR_PERCENT } from './config-schema.js'
import type { PerfConfig } from './config-schema.js'
import { exists } from './fs-probe.js'

/**
 * Renders `perf.yml` by hand rather than through a YAML serializer.
 *
 * The comments are the point — this file is the user's first look at the tool's model of their
 * project, and a bare key dump teaches them nothing. Serializer comment APIs make this harder to
 * read than a template does.
 */
export function renderConfig(config: PerfConfig): string {
  const measure =
    config.measure.length > 0
      ? `[${config.measure.join(', ')}]`
      : '[]                # nothing measurable was detected'

  return `# perf.yml — generated by driftwatch (edit only if you want to)
#
# Regenerate by deleting this file and running \`driftwatch init\`.
# Driftwatch never overwrites an existing perf.yml.

detect: ${config.detect}

# Metrics driftwatch will collect. Only metrics it can actually collect are listed —
# it will not promise a number it cannot produce.
measure: ${measure}

# The delta at which a change is called a regression.
# Separately and not configurable: anything under ${NOISE_FLOOR_PERCENT}% is treated as measurement
# noise and reported as "no change".
threshold: ${config.threshold}

# Boot the built app and measure route latency (Layer 2a). --no-serve skips per run.
serve: ${config.serve}

# Lighthouse browser metrics against the served app (needs Chrome). --no-browser skips per run.
browser: ${config.browser}

# Measure the AI's suggested diff fix in a fresh copy before showing it (M6). --no-verify skips.
verify: ${config.verify}

# "propose": when a verified fix RESTORES the regressed metrics, open a fix PR into your PR
# branch carrying the measured evidence. Off by default — turn it on once you trust the numbers.
auto_fix: ${config.auto_fix}

# Warn only. Set to true once you trust the numbers and want failing checks to block merges.
block_merge: ${config.block_merge}

# Default git ref to compare against. Override per run with --base.
base: ${config.base}

# AI analysis — the optional tier. Measurement never needs a key; explaining a regression does.
# Nothing is sent anywhere without one.
provider: ${config.provider}
model: ${config.model}

# Where the key comes from, in order:
#   1. DRIFTWATCH_API_KEY in the environment (your shell, or CI secrets)
#   2. key_command below — its stdout is used and never stored
#   3. ${'$'}{PROVIDER}_API_KEY you already have set (DEEPSEEK_API_KEY, OPENAI_API_KEY, …)
#
# NEVER put the key itself in this file — it is committed, and driftwatch refuses to run if it
# finds one here. A command is fine:
# key_command: op read op://vault/ai/key

# Hard ceiling on what ONE analysed regression may cost. Unset by default. When the projected
# cost exceeds it, driftwatch refuses the analysis rather than truncating it or switching models
# — the measurement and verdict are unaffected. Per-run only: driftwatch does not know your
# provider bill and does not track a running total.
# max_cost_per_run: 0.05
`
}

export interface WriteResult {
  readonly path: string
  readonly created: boolean
  readonly reason?: string
}

/**
 * Writes `perf.yml` if — and only if — it is absent.
 *
 * The user's file always wins. Regenerating it would silently discard a threshold someone tuned
 * deliberately, which is exactly the kind of quiet damage hard rule 2 exists to prevent.
 */
export async function writeConfigIfAbsent(
  projectRoot: string,
  config: PerfConfig,
): Promise<WriteResult> {
  const target = path.join(projectRoot, CONFIG_FILENAME)

  if (await exists(target)) {
    return { path: target, created: false, reason: 'already exists — left untouched' }
  }

  await writeFile(target, renderConfig(config), 'utf8')
  return { path: target, created: true }
}
