import path from 'node:path'
import { writeFile } from 'node:fs/promises'
import { parse } from 'yaml'
import type { Framework, MetricId, ProjectProfile } from './types.js'
import { exists, readText } from './fs-probe.js'

/**
 * `perf.yml` — generated by the tool, edited by the user only if they want to (spec §3.3).
 *
 * Two numbers that are easy to confuse live here, and only one of them is configurable:
 *
 *  - **noise floor, 2%** — below this we do not report a delta at all. It is a property of what the
 *    instrument can resolve (hard rule 4), not a preference, so it is not exposed as config.
 *  - **threshold, default 5%** — the line at which a reported delta becomes a *verdict*. That is a
 *    team judgement, so it is configurable.
 */

export const NOISE_FLOOR_PERCENT = 2

export const CONFIG_FILENAME = 'perf.yml'

export interface PerfConfig {
  readonly detect: Framework
  readonly measure: readonly MetricId[]
  readonly threshold: string
  readonly block_merge: boolean
  readonly base: string
  readonly provider: string
  readonly model: string
}

export const DEFAULT_CONFIG: PerfConfig = {
  detect: 'unknown',
  measure: [],
  threshold: '5%',
  block_merge: false,
  base: 'main',
  provider: 'deepseek',
  model: 'deepseek-chat',
}

/** Config as the rest of the tool consumes it: percentages parsed, defaults filled in. */
export interface ResolvedConfig extends PerfConfig {
  readonly thresholdPercent: number
  readonly noiseFloorPercent: number
  /** Absolute path the config was read from, or null when running on defaults. */
  readonly sourcePath: string | null
  readonly warnings: readonly string[]
}

export function configFromProfile(profile: ProjectProfile): PerfConfig {
  return {
    ...DEFAULT_CONFIG,
    detect: profile.framework,
    measure: [...profile.supportedMetrics],
  }
}

/**
 * Renders `perf.yml` by hand rather than through a YAML serializer.
 *
 * The comments are the point — this file is the user's first look at the tool's model of their
 * project, and a bare key dump teaches them nothing. Serializer comment APIs make this harder to
 * read than a template does.
 */
export function renderConfig(config: PerfConfig): string {
  const measure =
    config.measure.length > 0
      ? `[${config.measure.join(', ')}]`
      : '[]                # nothing measurable was detected'

  return `# perf.yml — generated by driftwatch (edit only if you want to)
#
# Regenerate by deleting this file and running \`driftwatch init\`.
# Driftwatch never overwrites an existing perf.yml.

detect: ${config.detect}

# Metrics driftwatch will collect. Only metrics it can actually collect are listed —
# it will not promise a number it cannot produce.
measure: ${measure}

# The delta at which a change is called a regression.
# Separately and not configurable: anything under ${NOISE_FLOOR_PERCENT}% is treated as measurement
# noise and reported as "no change".
threshold: ${config.threshold}

# Warn only. Set to true once you trust the numbers and want failing checks to block merges.
block_merge: ${config.block_merge}

# Default git ref to compare against. Override per run with --base.
base: ${config.base}

# AI analysis (unused until M2). Bring your own key; nothing is sent without one.
provider: ${config.provider}
model: ${config.model}
`
}

export interface WriteResult {
  readonly path: string
  readonly created: boolean
  readonly reason?: string
}

/**
 * Writes `perf.yml` if — and only if — it is absent.
 *
 * The user's file always wins. Regenerating it would silently discard a threshold someone tuned
 * deliberately, which is exactly the kind of quiet damage hard rule 2 exists to prevent.
 */
export async function writeConfigIfAbsent(
  projectRoot: string,
  config: PerfConfig,
): Promise<WriteResult> {
  const target = path.join(projectRoot, CONFIG_FILENAME)

  if (await exists(target)) {
    return { path: target, created: false, reason: 'already exists — left untouched' }
  }

  await writeFile(target, renderConfig(config), 'utf8')
  return { path: target, created: true }
}

/**
 * Loads `perf.yml`, falling back to detected defaults for anything missing or malformed.
 *
 * A broken config never aborts a run — it degrades to defaults and says so, per the convention that
 * errors are recorded rather than fatal.
 */
export async function loadConfig(
  projectRoot: string,
  fallback: PerfConfig = DEFAULT_CONFIG,
): Promise<ResolvedConfig> {
  const target = path.join(projectRoot, CONFIG_FILENAME)
  const raw = await readText(target)
  const warnings: string[] = []

  if (raw === null) {
    return resolve(fallback, null, warnings)
  }

  let parsed: unknown
  try {
    parsed = parse(raw)
  } catch (error) {
    warnings.push(
      `${CONFIG_FILENAME} could not be parsed (${(error as Error).message}) — using detected defaults.`,
    )
    return resolve(fallback, target, warnings)
  }

  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    warnings.push(`${CONFIG_FILENAME} is not a YAML mapping — using detected defaults.`)
    return resolve(fallback, target, warnings)
  }

  const record = parsed as Record<string, unknown>
  const config: PerfConfig = {
    detect: pickFramework(record.detect, fallback.detect, warnings),
    measure: pickMetrics(record.measure, fallback.measure, warnings),
    threshold: pickString(record.threshold, fallback.threshold, 'threshold', warnings),
    block_merge: pickBoolean(record.block_merge, fallback.block_merge, warnings),
    base: pickString(record.base, fallback.base, 'base', warnings),
    provider: pickString(record.provider, fallback.provider, 'provider', warnings),
    model: pickString(record.model, fallback.model, 'model', warnings),
  }

  for (const key of Object.keys(record)) {
    if (!(key in DEFAULT_CONFIG)) {
      warnings.push(`${CONFIG_FILENAME}: unknown key "${key}" ignored.`)
    }
  }

  return resolve(config, target, warnings)
}

function resolve(
  config: PerfConfig,
  sourcePath: string | null,
  warnings: string[],
): ResolvedConfig {
  const parsedThreshold = parsePercent(config.threshold)
  if (parsedThreshold === null) {
    warnings.push(
      `${CONFIG_FILENAME}: threshold "${config.threshold}" is not a percentage — using ${DEFAULT_CONFIG.threshold}.`,
    )
  }

  return {
    ...config,
    thresholdPercent: parsedThreshold ?? parsePercent(DEFAULT_CONFIG.threshold)!,
    noiseFloorPercent: NOISE_FLOOR_PERCENT,
    sourcePath,
    warnings,
  }
}

/** Accepts `5%`, `5`, or `5.5%`. */
export function parsePercent(value: string): number | null {
  const match = /^\s*(\d+(?:\.\d+)?)\s*%?\s*$/.exec(value)
  if (!match?.[1]) return null
  const n = Number(match[1])
  return Number.isFinite(n) ? n : null
}

const KNOWN_METRICS: readonly MetricId[] = ['build_time', 'bundle_size', 'install_time']

function pickFramework(value: unknown, fallback: Framework, warnings: string[]): Framework {
  if (value === 'nextjs' || value === 'unknown') return value
  if (value !== undefined) {
    warnings.push(`${CONFIG_FILENAME}: unsupported detect "${String(value)}" — using "${fallback}".`)
  }
  return fallback
}

function pickMetrics(
  value: unknown,
  fallback: readonly MetricId[],
  warnings: string[],
): readonly MetricId[] {
  if (value === undefined) return fallback
  if (!Array.isArray(value)) {
    warnings.push(`${CONFIG_FILENAME}: measure must be a list — using detected metrics.`)
    return fallback
  }

  const kept: MetricId[] = []
  for (const entry of value) {
    if (typeof entry === 'string' && (KNOWN_METRICS as readonly string[]).includes(entry)) {
      kept.push(entry as MetricId)
    } else {
      warnings.push(`${CONFIG_FILENAME}: unknown metric "${String(entry)}" ignored.`)
    }
  }
  return kept
}

function pickString(value: unknown, fallback: string, key: string, warnings: string[]): string {
  if (typeof value === 'string' && value.trim() !== '') return value.trim()
  if (typeof value === 'number') return String(value)
  if (value !== undefined) {
    warnings.push(`${CONFIG_FILENAME}: ${key} must be a string — using "${fallback}".`)
  }
  return fallback
}

function pickBoolean(value: unknown, fallback: boolean, warnings: string[]): boolean {
  if (typeof value === 'boolean') return value
  if (value !== undefined) {
    warnings.push(`${CONFIG_FILENAME}: block_merge must be true or false — using ${fallback}.`)
  }
  return fallback
}
