import { DRIFTWATCH_VERSION } from '../../core/index.js'
/** This repository's own name. A workflow generated HERE must run the local action. */
export const SELF_PACKAGE = '@ahmednaguib/driftwatch'

/**
 * The published Action, pinned to THIS build's version — never a hardcoded tag, which would lag
 * the next release silently. A workflow therefore pins the exact driftwatch that generated it,
 * which is the same guarantee the protocol hash makes about the measurement.
 */
export const PUBLISHED_ACTION = `AhmedNaguib20/Driftwatch@v${DRIFTWATCH_VERSION}`

export interface WorkflowOptions {
  readonly projectDir?: string
  /**
   * True only when generating for driftwatch's OWN repository, where the workflow must run the
   * action being changed rather than the last published one — otherwise every PR check here
   * would measure released code and say nothing about the diff under review.
   *
   * Everywhere else this is false, and the workflow references the published Action. It was
   * hardcoded to the local form until v0.6.0, which meant `init --github` wrote a file into a
   * user's repository that could not run: `uses: ./` looks for an action.yml they do not have.
   */
  readonly self?: boolean
}

/** The workflow `driftwatch init --github` writes. One template, commented for its reader. */
export function renderWorkflow(options: WorkflowOptions | string = {}): string {
  const { projectDir = '.', self = false } =
    typeof options === 'string' ? { projectDir: options, self: false } : options
  const runStep = self
    ? `      # Driftwatch's own repository: build the action from this checkout and run THAT, so a
      # pull request measures the code it is changing rather than the last release.
      - run: npm ci && npm run build

      - uses: ./`
    : `      # Pinned deliberately, like the Chrome version above. driftwatch's own version is part
      # of the measurement protocol, so upgrading it starts a new trend segment — that break
      # should be a dated decision you made, not something a floating tag did to your history.
      - uses: ${PUBLISHED_ACTION}`
  return `# Generated by \`driftwatch init --github\` — edit freely; driftwatch never overwrites
# this file without --force.
name: driftwatch

on:
  pull_request:          # compare mode: did this change regress?
  push:
    branches: [main]     # record mode: append main's trend point to the perf-data branch
                         # The branch also carries a self-contained index.html dashboard.
                         # One-time (optional): Settings → Pages → Deploy from a branch →
                         # perf-data / root — driftwatch never changes repo settings itself.
  schedule:
    - cron: '17 6 * * 1' # drift alerting: reads the recorded history, measures nothing.
                         # Weekly, because drift is an accumulation over many commits — and
                         # because an alert fires once per condition, a faster cadence would
                         # mostly re-read a state it has already agreed to stay quiet about.
  workflow_dispatch:     # the same check, on demand

# A superseded push should not waste a measurement (~2-4 minutes each).
concurrency:
  group: driftwatch-\${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write        # record mode pushes trend points to the perf-data branch;
                         # with auto_fix: propose it also pushes driftwatch/fix-pr<N> branches
  pull-requests: write   # the self-updating PR comment — and fix PRs when auto_fix is on
# auto_fix: propose additionally requires a REPO SETTING (driftwatch documents it, never flips it):
#   Settings → Actions → General → Workflow permissions →
#   ✓ "Allow GitHub Actions to create and approve pull requests"
# Without it, GitHub returns 403 on PR creation; the run still succeeds and the comment says
# a verified fix exists but the PR could not be opened.
  checks: write          # the non-blocking check run
  issues: write          # drift alerts open ONE issue per condition and maintain it in place

jobs:
  driftwatch:
    # Measurement modes only. The scheduled drift check measures nothing and shares none of this.
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    # A hung setup step (observed: apt inside setup-chrome stalling for an hour) must never eat
    # the 6-hour default. A full run is ~10 minutes; anything past this is wedged, not slow.
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
        with:
          # Required: driftwatch checks the PR base commit out into a temporary worktree.
          # The default shallow clone (depth 1) does not contain it.
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Chrome is PINNED (spec §5.1): the browser build is part of the measurement protocol, and
      # shared runners churn Chrome builds mid-day — three builds were observed in one day, each
      # one a protocol break that splits the trend. Bumping this version is a deliberate,
      # one-break upgrade: change it, expect exactly one break marker in the dashboard.
      - uses: browser-actions/setup-chrome@v2
        id: chrome
        with:
          chrome-version: 151.0.7922.77
          # ^ a Chrome-for-Testing known-good build. Two hard-won notes: not every stable build
          #   is published to CfT, and "published" does not mean "works" — 151.0.7922.138
          #   installs fine but its DevTools endpoint resets connections on ubuntu-24 runners
          #   (child-process crashes; diagnosed via trend-point skip reasons). Test a pin bump
          #   on one push before trusting it.
          install-dependencies: true      # CfT builds need shared libraries the bare runner lacks

${runStep}
        with:
          project-dir: ${projectDir}
        env:
          # Both modes (PR compare and record) measure with the same pinned browser.
          CHROME_PATH: \${{ steps.chrome.outputs.chrome-path }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          # AI analysis (optional, BYOK). Add your DeepSeek or OpenAI key under
          # Settings → Secrets and variables → Actions → "DRIFTWATCH_API_KEY".
          # Without it, regressions are still measured and reported — just not explained.
          DRIFTWATCH_API_KEY: \${{ secrets.DRIFTWATCH_API_KEY }}

  # Drift alerting (spec §9b). No Chrome, no build of your app, no measurement: it reads the
  # perf-data branch and asks whether anything has drifted past the alert line within one
  # protocol segment. Silence is the expected outcome, and the log says so in one line.
  alerts:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Only the perf-data branch is read, and driftwatch fetches that itself — the working tree
      # here is never measured, so a shallow clone is enough.
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

${runStep}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
`
}

export const WORKFLOW_PATH = '.github/workflows/driftwatch.yml'
