/** The workflow `driftwatch init --github` writes. One template, commented for its reader. */
export function renderWorkflow(projectDir = '.'): string {
  return `# Generated by \`driftwatch init --github\` — edit freely; driftwatch never overwrites
# this file without --force.
name: driftwatch

on:
  pull_request:          # compare mode: did this change regress?
  push:
    branches: [main]     # record mode: append main's trend point to the perf-data branch
                         # The branch also carries a self-contained index.html dashboard.
                         # One-time (optional): Settings → Pages → Deploy from a branch →
                         # perf-data / root — driftwatch never changes repo settings itself.

# A superseded push should not waste a measurement (~2-4 minutes each).
concurrency:
  group: driftwatch-\${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write        # record mode pushes trend points to the perf-data branch
  pull-requests: write   # the self-updating PR comment
  checks: write          # the non-blocking check run

jobs:
  driftwatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Required: driftwatch checks the PR base commit out into a temporary worktree.
          # The default shallow clone (depth 1) does not contain it.
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Developing driftwatch in this repo: build the local action and run it.
      # Once driftwatch is published, these two steps become a single
      #   - uses: driftwatch/action@v1
      - run: npm ci && npm run build

      - uses: ./
        with:
          project-dir: ${projectDir}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          # AI analysis (optional, BYOK). Add your DeepSeek or OpenAI key under
          # Settings → Secrets and variables → Actions → "DRIFTWATCH_API_KEY".
          # Without it, regressions are still measured and reported — just not explained.
          DRIFTWATCH_API_KEY: \${{ secrets.DRIFTWATCH_API_KEY }}
`
}

export const WORKFLOW_PATH = '.github/workflows/driftwatch.yml'
