/** The workflow `driftwatch init --github` writes. One template, commented for its reader. */
export function renderWorkflow(projectDir = '.'): string {
  return `# Generated by \`driftwatch init --github\` — edit freely; driftwatch never overwrites
# this file without --force.
name: driftwatch

on:
  pull_request:          # compare mode: did this change regress?
  push:
    branches: [main]     # record mode: append main's trend point to the perf-data branch
                         # The branch also carries a self-contained index.html dashboard.
                         # One-time (optional): Settings → Pages → Deploy from a branch →
                         # perf-data / root — driftwatch never changes repo settings itself.

# A superseded push should not waste a measurement (~2-4 minutes each).
concurrency:
  group: driftwatch-\${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write        # record mode pushes trend points to the perf-data branch
  pull-requests: write   # the self-updating PR comment
  checks: write          # the non-blocking check run

jobs:
  driftwatch:
    runs-on: ubuntu-latest
    # A hung setup step (observed: apt inside setup-chrome stalling for an hour) must never eat
    # the 6-hour default. A full run is ~10 minutes; anything past this is wedged, not slow.
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
        with:
          # Required: driftwatch checks the PR base commit out into a temporary worktree.
          # The default shallow clone (depth 1) does not contain it.
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Chrome is PINNED (spec §5.1): the browser build is part of the measurement protocol, and
      # shared runners churn Chrome builds mid-day — three builds were observed in one day, each
      # one a protocol break that splits the trend. Bumping this version is a deliberate,
      # one-break upgrade: change it, expect exactly one break marker in the dashboard.
      - uses: browser-actions/setup-chrome@v2
        id: chrome
        with:
          chrome-version: 151.0.7922.77  # a Chrome-for-Testing known-good build (not every stable build is published)
          install-dependencies: true      # CfT builds need shared libraries the bare runner lacks

      # Developing driftwatch in this repo: build the local action and run it.
      # Once driftwatch is published, these two steps become a single
      #   - uses: driftwatch/action@v1
      - run: npm ci && npm run build

      - uses: ./
        with:
          project-dir: ${projectDir}
        env:
          # Both modes (PR compare and record) measure with the same pinned browser.
          CHROME_PATH: \${{ steps.chrome.outputs.chrome-path }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          # AI analysis (optional, BYOK). Add your DeepSeek or OpenAI key under
          # Settings → Secrets and variables → Actions → "DRIFTWATCH_API_KEY".
          # Without it, regressions are still measured and reported — just not explained.
          DRIFTWATCH_API_KEY: \${{ secrets.DRIFTWATCH_API_KEY }}
`
}

export const WORKFLOW_PATH = '.github/workflows/driftwatch.yml'
